config/routes.rb
Rails.application.routes.draw do
  resources :oyatsus
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    {id: 1, name: 'チップス'},
    {id: 2, name: 'スナック菓子'},
    {id: 3, name: 'スティック菓子'},
    {id: 4, name: 'グミ'},
    {id: 5, name: 'アメ'},
    {id: 6, name: 'ガム'},
    {id: 7, name: 'チョコレート'},
    {id: 8, name: 'アイス'},
    {id: 9, name: 'パン'},
    {id: 10, name: '飲み物'},
    {id: 11, name: 'その他'},
  ]
end

app/models/oyatsu.rb
class Oyatsu < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category

  mount_uploader :image, ImageUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/oyatsus_controller.rb
class OyatsusController < ApplicationController
  before_action :set_oyatsu, only: [:show, :edit, :update, :destroy]

  # GET /oyatsus
  # GET /oyatsus.json
  def index
    @oyatsus = Oyatsu.all
  end

  # GET /oyatsus/1
  # GET /oyatsus/1.json
  def show
  end

  # GET /oyatsus/new
  def new
    @oyatsu = Oyatsu.new
  end

  # GET /oyatsus/1/edit
  def edit
  end

  # POST /oyatsus
  # POST /oyatsus.json
  def create
    @oyatsu = Oyatsu.new(oyatsu_params)

    respond_to do |format|
      if @oyatsu.save
        format.html { redirect_to @oyatsu, notice: 'Oyatsu was successfully created.' }
        format.json { render :show, status: :created, location: @oyatsu }
      else
        format.html { render :new }
        format.json { render json: @oyatsu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /oyatsus/1
  # PATCH/PUT /oyatsus/1.json
  def update
    respond_to do |format|
      if @oyatsu.update(oyatsu_params)
        format.html { redirect_to @oyatsu, notice: 'Oyatsu was successfully updated.' }
        format.json { render :show, status: :ok, location: @oyatsu }
      else
        format.html { render :edit }
        format.json { render json: @oyatsu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /oyatsus/1
  # DELETE /oyatsus/1.json
  def destroy
    @oyatsu.destroy
    respond_to do |format|
      format.html { redirect_to oyatsus_url, notice: 'Oyatsu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_oyatsu
      @oyatsu = Oyatsu.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def oyatsu_params
      params.require(:oyatsu).permit(:name, :category_id, :image, :detail, :maker, :watch_at, :site_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/oyatsus_helper.rb
module OyatsusHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | OyatsuBase
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/oyatsus/_form.html.slim
= simple_form_for(@oyatsu) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name, input_html: {size: 50}
    = f.input :category, as: :select, collection: Category.all
    = f.input :image
    = f.input :detail
    = f.input :maker
    = f.input :watch_at
    = f.input :site_url

  .form-actions
    => f.button :submit, class: "btn btn-primary"
    =< link_to t('simple_form.btn.back'), @oyatsu, class: "btn btn-secondary"

app/views/oyatsus/edit.html.slim
h1 Editing oyatsu

== render 'form'

=> link_to 'Show', @oyatsu
'|
=< link_to 'Back', oyatsus_path

app/views/oyatsus/index.html.slim
h1 Listing oyatsus

table
  thead
    tr
      th Name
      th Category
      th Image
      th Detail
      th Maker
      th Watch at
      th Site url
      th
      th
      th

  tbody
    - @oyatsus.each do |oyatsu|
      tr
        td = oyatsu.name
        td = oyatsu.category.name
        td = oyatsu.image
        td = oyatsu.detail
        td = oyatsu.maker
        td = oyatsu.watch_at
        td = oyatsu.site_url
        td = link_to 'Show', oyatsu
        td = link_to 'Edit', edit_oyatsu_path(oyatsu)
        td = link_to 'Destroy', oyatsu, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Oyatsu', new_oyatsu_path

app/views/oyatsus/new.html.slim
h1 New oyatsu

== render 'form'

= link_to 'Back', oyatsus_path

app/views/oyatsus/show.html.slim
p#notice = notice

p
  strong Name:
  = @oyatsu.name
p
  strong Category:
  = @oyatsu.category.name
p
  strong Image:
  - if @oyatsu.image?
    = image_tag @oyatsu.image.url
p
  strong Detail:
  = @oyatsu.detail
p
  strong Maker:
  = @oyatsu.maker
p
  strong Watch at:
  = @oyatsu.watch_at
p
  strong Site url:
  = @oyatsu.site_url

=> link_to 'Edit', edit_oyatsu_path(@oyatsu)
'|
=< link_to 'Back', oyatsus_path